### ISSUE TITLE
how to train my model based on the checkpoint model

### ISSUE THREAD

**Issue by skyfallsss** [enyac-group/supmae#2]
I want to train my model based on the checkpoint model

**Comment by Jeff-LiangF** [comment]
Hey @skyfallsss, Can you elaborate more on the questions? If you are thinking about transferring the checkpoint to your tasks, you can directly load the checkpoint (the model is `timm.vision_transformer` format). If you are thinking about pre-training your model, check out the [pre-training](https://github.com/cmu-enyac/supmae/blob/main/PRETRAIN.md).

I've closed the issue, feel free to reopen it. Thanks.

**Comment by skyfallsss** [comment]
I want to train my model by using checkpoint model you provide.

**Comment by Jeff-LiangF** [comment]
@skyfallsss Cool! You can simply use the pre-trained model [here](https://drive.google.com/file/d/1YwcTJvASZJvn2LxyZZG4PcgXaBCKEv_4/view?usp=sharing). It is exactly the same model as in `timm.vision_transformer`
