### ISSUE TITLE
Question about robustness of the model.

### ISSUE THREAD

**Issue by geonuk-kimmm** [enyac-group/supmae#3]
Thanks for nice paper and releasing the source code.
I see that your method resolves training burden of MAE.
And, how about robustness? is there any experimental result with IN-C or IN-A?
<img width="809" alt="image" src="https://user-images.githubusercontent.com/34879386/174761287-0ad5a10c-96ae-4aeb-b354-c4f09122503f.png">

**Comment by Jeff-LiangF** [comment]
@mandal4 Thanks for your advice! We haven't tested on the ImageNet variants yet, but it's definitely worth to try! We hope to report them in the next updated version.

**Comment by Jeff-LiangF** [comment]
Hi @mandal4, I finally had time to test the robustness of these four ImageNet variants. Using the provided fine-tuned checkpoint, we can get:

|                 | MAE  | SupMAE(Ours) |
|-----------------|------|--------------|
| IN-Corruption ↓ | 51.7 | 48.1         |
| IN-Adversarial  | 35.9 | 35.5         |
| IN-Rendition    | 48.3 | 51.0         |
| IN-Sketch       | 34.5 | 36.0         |

Our SupMAE learns a more robust model than MAE. See Table 2 for the updated [arxiv](https://arxiv.org/pdf/2205.14540.pdf) for more details. Thank you!
